import type { LevelDef } from "./types";

/**
 * Map legend
 *  # wall   . floor   @ Osea   & Lois
 *  $ stone box   W wood (Osea burns)   i ice (Lois shatters)
 *  E exit   F lava (only Osea)   ~ water (only Lois)
 *  1-9 pressure plate channel   A-I gate (A=1 … I=9)
 *  * astral shard   k golden key   d locked door
 */
export const LEVELS: LevelDef[] = [
  {
    id: "1",
    title: "Primii pași",
    chapter: "Grădina de Piatră",
    lesson: "Mișcare și schimb",
    theme: "meadow",
    par: 14,
    hint: "Săgeți sau WASD ca să mergi. Tab schimbă între Osea și Lois. Du-i pe amândoi pe portal.",
    map: [
      "###########",
      "#@......E.#",
      "#.........#",
      "#....*....#",
      "#.........#",
      "#&......E.#",
      "###########",
    ],
  },
  {
    id: "2",
    title: "Cutii și coridoare",
    chapter: "Grădina de Piatră",
    lesson: "Împinge și ocolește",
    theme: "meadow",
    par: 16,
    hint: "Împinge cutiile dincolo de portal ca să nu-ți blochezi drumul. O cutie nu poate fi trasă înapoi.",
    map: [
      "#############",
      "#@..$....E..#",
      "#...........#",
      "#....###....#",
      "#...........#",
      "#&..$....E..#",
      "#############",
    ],
  },
  {
    id: "3",
    title: "Ecouri de lumină",
    chapter: "Grădina de Piatră",
    lesson: "Fragmente astrale",
    theme: "meadow",
    par: 27,
    requireOrbs: true,
    hint: "Portalurile sunt adormite. Adunați toate cele trei fragmente astrale înainte să încercați ieșirea.",
    map: [
      "#############",
      "#@..*.......#",
      "#...###.....#",
      "#.*.....*...#",
      "#.....###...#",
      "#&........EE#",
      "#############",
    ],
  },
  {
    id: "4",
    title: "Poarta veche",
    chapter: "Ruinele Adormite",
    lesson: "Plăci de presiune",
    theme: "ruins",
    par: 23,
    requireOrbs: true,
    hint: "Lasă cutia pe placa numerotată. Poarta rămâne deschisă numai cât timp placa este apăsată.",
    map: [
      "###########",
      "#@........#",
      "#...$..1..#",
      "#&........#",
      "#####A#####",
      "#..*..EE..#",
      "###########",
    ],
  },
  {
    id: "5",
    title: "Cheia de aur",
    chapter: "Ruinele Adormite",
    lesson: "Chei și uși",
    theme: "ruins",
    par: 30,
    requireOrbs: true,
    hint: "Ridică cheia aurie. Din acel moment ușa încuiată se deschide pentru amândoi. Nu uita fragmentele.",
    map: [
      "###############",
      "#@....k.......#",
      "#.#####.#####.#",
      "#.....*.......#",
      "#####d#########",
      "#.....*.......#",
      "#&.........EE.#",
      "###############",
    ],
  },
  {
    id: "6",
    title: "Jarul lui Osea",
    chapter: "Forja de Chihlimbar",
    lesson: "Foc și cooperare",
    theme: "ember",
    par: 19,
    requireOrbs: true,
    hint: "Spațiu lansează flacăra lui Osea. Arde lemnul din față — inclusiv obstacolele care îl blochează pe Lois.",
    map: [
      "#############",
      "#@..W.*...E.#",
      "#.....#.....#",
      "#.....#.....#",
      "#&....W...E.#",
      "#############",
    ],
  },
  {
    id: "7",
    title: "Respirația apei",
    chapter: "Grota Albastră",
    lesson: "Bule și gheață",
    theme: "tide",
    par: 19,
    requireOrbs: true,
    hint: "Lois sparge cristalele de gheață cu bulele ei. Osea nu poate distruge gheața.",
    map: [
      "#############",
      "#@........E.#",
      "#.....#.....#",
      "#.....#.....#",
      "#&..i.*...E.#",
      "#############",
    ],
  },
  {
    id: "8",
    title: "Foc și apă",
    chapter: "Hotarul Elementelor",
    lesson: "Terenuri elementale",
    theme: "sanctum",
    par: 24,
    hint: "Lava o traversează doar Osea. Apa o traversează doar Lois. Fiecare are drumul lui.",
    map: [
      "###############",
      "#@..FFFFF....E#",
      "###############",
      "#&..~~~~~....E#",
      "###############",
    ],
  },
  {
    id: "9",
    title: "Podul imposibil",
    chapter: "Hotarul Elementelor",
    lesson: "Cutia devine pod",
    theme: "sanctum",
    par: 23,
    hint: "O cutie împinsă pe apă sau lavă devine o insulă sigură. Folosește-o ca pod pentru personajul vulnerabil.",
    map: [
      "##############",
      "#@.$.....~..E#",
      "#.....*......#",
      "#&..$....F..E#",
      "##############",
    ],
  },
  {
    id: "10",
    title: "Sigiliul",
    chapter: "Templul Dublu",
    lesson: "Cheie, foc și gheață",
    theme: "ruins",
    par: 20,
    requireOrbs: true,
    hint: "Arde lemnul, sparge gheața, adună cheia și fragmentele. Ușa centrală leagă cele două jumătăți ale templului.",
    map: [
      "###########",
      "#@.k.*....#",
      "#..W......#",
      "#####d#####",
      "#&..i.*.EE#",
      "###########",
    ],
  },
  {
    id: "11",
    title: "Ține-mi poarta",
    chapter: "Templul Dublu",
    lesson: "Cooperare pură",
    theme: "tide",
    par: 16,
    requireOrbs: true,
    plateIsExit: [2],
    hint: "Unul trebuie să rămână pe placa-portal ca să țină poarta deschisă pentru celălalt. Ordinea contează.",
    map: [
      "###########",
      "#@....2E..#",
      "#..*......#",
      "#######B###",
      "#&........#",
      "###########",
    ],
  },
  {
    id: "12",
    title: "Inima Labirintului",
    chapter: "Sanctuarul",
    lesson: "Finala elementală",
    theme: "sanctum",
    par: 27,
    requireOrbs: true,
    hint: "Tot ce ai învățat: foc, gheață, cutie, placă, poartă, cheie, ușă și fragment. Fă drumul pentru amândoi.",
    map: [
      "#############",
      "#@.W.$1.k...#",
      "######A######",
      "#&.i.*..d.EE#",
      "#############",
    ],
  },
];

export function levelCount() {
  return LEVELS.length;
}
